ClusterManager; added minClusterSize as option
sharewire/google-maps-clustering pull request #9
Opened 2018-01-31 09:47 UTC by meierjan

2018-01-31 09:50 UTC, meierjan commented
Problem:
Many times the cluster only contain 2 or 3 items even if there would - for some tastes - be enough space to display them individually.

Solution:
The `ClusterManager` can now receive a 'minClusterSize' so that it will not start clustering until a certain amount of items is reached.

2018-01-31 09:50 UTC, meierjan commented
Related to issue #7

2018-02-01 08:56 UTC, makovkastar commented
Thank you, I will take a look as soon as I have time.

2018-02-02 15:33 UTC, makovkastar requested changes

2018-02-02 15:33 UTC, makovkastar commented on library/src/main/java/net/sharewire/googlemapsclustering/ClusterManager.java
> +        this.mMinClusterSize = minClusterSize;
No need for `this`.

2018-02-02 15:33 UTC, makovkastar commented on library/src/main/java/net/sharewire/googlemapsclustering/ClusterManager.java
> +        }
I would add a new method to `Preconditions.java`:

```
 static void checkArgument(boolean expression) {
    if (!expression) {
      throw new IllegalArgumentException();
    }
  }
```

And then use it:

```
checkArgument(minClusterSize > 0);
mMinClusterSize = minClusterSize;
```

2018-02-02 15:33 UTC, makovkastar commented on library/src/main/java/net/sharewire/googlemapsclustering/ClusterManager.java
> +        final List<Cluster<T>> clusters = new ArrayList<>();
We don't use final for local variables in this library.

2018-02-02 15:33 UTC, makovkastar commented on library/src/main/java/net/sharewire/googlemapsclustering/ClusterManager.java
> +    private int mMinClusterSize = 1;
I prefer to have a constant `DEFAULT_MIN_CLUSTER_SIZE = 1` and then `private int mMinClusterSize = DEFAULT_MIN_CLUSTER_SIZE`.

2018-02-02 15:33 UTC, makovkastar commented on library/src/main/java/net/sharewire/googlemapsclustering/ClusterManager.java
> +                                )
I prefer the formatting that was here before.

2018-02-02 15:33 UTC, makovkastar commented on library/src/main/java/net/sharewire/googlemapsclustering/ClusterManager.java
> +                            );
I prefer the formatting that was here before.

2018-02-02 15:33 UTC, makovkastar commented on library/src/main/java/net/sharewire/googlemapsclustering/ClusterManager.java
> +                        for (QuadTreePoint point : points) {
Replace QuadTreePoint with T.

2018-02-03 00:36 UTC, meierjan commented
there you go.

2018-02-03 11:53 UTC, makovkastar commented
Good work! Could you squash the changes into a single commit with a descriptive name and I will merge it?

2018-02-03 11:57 UTC, makovkastar approved these changes

2018-02-03 11:59 UTC, meierjan commented
there u go.

2018-02-03 12:01 UTC, merged

2018-02-06 14:35 UTC, PJHaynes304 commented
This is a great feature! Is there any of chance of a new version being pushed to bintray so that we can use the new feature when using the library through gradle dependency?

2018-02-06 14:36 UTC, makovkastar commented
I will push a new version to Bintray as soon as possible.

2018-02-06 14:38 UTC, PJHaynes304 commented
Appreciate it, thanks!

2018-02-07 18:54 UTC, makovkastar commented
The new version 0.1.3 has been released to Bintray.

2018-02-08 11:32 UTC, PJHaynes304 commented
Great, thanks! just built with the new version and having a play around with the minimum cluster size. @meierjan would you expect this to work when dynamically changed? I'm setting a minimum cluster size at a certain zoom level to essentially disable clustering for items that have duplicate locations. When zoomed back out, after I reassign the default minimum cluster size to 1 the items aren't reclustered. Is this expected behaviour?

2018-02-08 11:51 UTC, meierjan commented
Hey @PJHaynes304, I did this intensional. But yeah, I had the same question in mind and I think this should be discusses. I'd like to hear @makovkastar on that as well.

As a workaround I think you can call `ClusterManager#onCameraIdle` after setting the size - if I recall correctly.